-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE public."Users"
(
    "Id" integer,
    "Email" character varying(50),
    "Password" character(30),
    PRIMARY KEY ("Id")
);

CREATE TABLE public."SystemUsers"
(
    "UserId" integer,
    "OperationClaimName" character varying(250),
    PRIMARY KEY ("UserId")
);

CREATE TABLE public."Candidates"
(
    "UserId" integer,
    "FirstName" character varying(50),
    "LastName" character varying(50),
    "NationalityId" character(11),
    "DateOfBirth" date,
    PRIMARY KEY ("UserId")
);

CREATE TABLE public."Employers"
(
    "UserId" integer,
    "CompanyName" character varying(50),
    "WebAddress" character varying(150),
    "PhoneNo" character(10),
    PRIMARY KEY ("UserId")
);

CREATE TABLE public."JobPositions"
(
    "Id" integer,
    "EmployerId" integer,
    "JobPositionName" character varying(50),
    PRIMARY KEY ("Id")
);

CREATE TABLE public."EmailVerifications"
(
    "Id" integer,
    "UserId" integer,
    "EmailVerified" boolean,
    "DateOfVerification" date,
    PRIMARY KEY ("Id")
);

CREATE TABLE public."SystemVerifications"
(
    "Id" integer,
    "EmployerId" integer,
    "SystemVerified" boolean,
    "DateOfVerification" date,
    PRIMARY KEY ("Id")
);

ALTER TABLE public."Users"
    ADD FOREIGN KEY ("Id")
    REFERENCES public."SystemUsers" ("UserId")
    NOT VALID;


ALTER TABLE public."Users"
    ADD FOREIGN KEY ("Id")
    REFERENCES public."Candidates" ("UserId")
    NOT VALID;


ALTER TABLE public."Users"
    ADD FOREIGN KEY ("Id")
    REFERENCES public."Employers" ("UserId")
    NOT VALID;


ALTER TABLE public."Employers"
    ADD FOREIGN KEY ("UserId")
    REFERENCES public."JobPositions" ("EmployerId")
    NOT VALID;


ALTER TABLE public."Users"
    ADD FOREIGN KEY ("Id")
    REFERENCES public."JobPositions" ("EmployerId")
    NOT VALID;


ALTER TABLE public."Employers"
    ADD FOREIGN KEY ("UserId")
    REFERENCES public."SystemVerifications" ("EmployerId")
    NOT VALID;


ALTER TABLE public."Users"
    ADD FOREIGN KEY ("Id")
    REFERENCES public."EmailVerifications" ("UserId")
    NOT VALID;

END;